
import React from 'react';

const Disclaimer: React.FC = () => {
  return (
    <footer className="mt-12 text-center text-[var(--color-text-secondary)] text-sm border-t border-[var(--color-border)] pt-6">
      <p className="font-bold mb-2 text-gray-400">Disclaimer: For Educational Purposes Only</p>
      <p>
        This tool is a simplified interpretation of Benjamin Graham's valuation formula and is intended for educational purposes only. It does not constitute financial, investment, or any other form of advice. The data is generated by an AI model and may not be accurate or up-to-date. Always conduct your own thorough research and consult with a qualified financial advisor before making any investment decisions.
      </p>
    </footer>
  );
};

export default Disclaimer;